---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "tar"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: "Create directory"
  become_user: true
  file:
    path: ~/udapeople/
    state: directory


- name: "deploy backend"
  become_user: true
  unarchive:
    src: /etc/artifact.tar.gz
    dest: ~/udapeople/

- name: "run backend"
  become_user: true
  shell: |
    cd ~/udapeople/
    npm i
    pm2 start npm -- run start
