


- name: "Create directory"
  become_user: true
  file:
    path: ~/udapeople/
    state: directory


- name: "deploy backend"
  become_user: true
  unarchive:
    src: /etc/artifact.tar.gz
    dest: ~/udapeople/

- name: "run backend"
  become_user: true
  shell: |
    cd ~/udapeople/
    npm i
    pm2 start npm -- run start
