---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "tar"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present



- name: "copy backend folder"
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu
- name: Install Node Dependencies
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo npm install
- name: Install Node Dependencies
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo npm audit fix --audit-level=critical --force
- name: Building backend service
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo npm run build

- name: "run migrations again"
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo npm run migrations

- name: Running backend service
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo pm2 start npm --no-automation --name "backend" -- run start
